/**
 * nrc-lexicon.js
 * NRC Word-Emotion Association Lexicon — embedded subset (~700 words)
 *
 * Emotions encoded as a bitmask (10 bits):
 *   1=anger  2=anticipation  4=disgust  8=fear
 *  16=joy   32=sadness      64=surprise 128=trust  256=negative  512=positive
 *
 * Based on the NRC Emotion Lexicon by Saif Mohammad (NRC, Canada).
 * This embedded subset covers the most emotionally significant vocabulary
 * for song lyrics, poetry, and everyday expressive text.
 */
window.NRC_DATA = {
  // --- A ---
  abandon:      296,  // fear+sadness+negative
  abhor:        261,  // anger+disgust+negative
  abomination:  269,  // anger+disgust+fear+negative
  absence:      288,  // sadness+negative
  abuse:        301,  // anger+disgust+fear+sadness+negative
  ache:         288,  // sadness+negative
  achieve:      658,  // anticipation+joy+trust+positive
  achievement:  658,  // anticipation+joy+trust+positive
  admire:       656,  // joy+trust+positive
  adventure:    594,  // anticipation+joy+surprise+positive
  affection:    656,  // joy+trust+positive
  afraid:       264,  // fear+negative
  agony:        297,  // anger+fear+sadness+negative
  aggression:   257,  // anger+negative
  aggressive:   257,  // anger+negative
  alive:        530,  // anticipation+joy+positive
  alone:        288,  // sadness+negative
  amazing:      594,  // anticipation+joy+surprise+positive
  ambition:     642,  // anticipation+trust+positive
  anger:        257,  // anger+negative
  angry:        257,  // anger+negative
  annoy:        257,  // anger+negative
  annoying:     261,  // anger+disgust+negative
  anxiety:      296,  // fear+sadness+negative
  anxious:      296,  // fear+sadness+negative
  appreciate:   656,  // joy+trust+positive
  arrogant:     261,  // anger+disgust+negative
  astonish:     594,  // anticipation+joy+surprise+positive
  attack:       265,  // anger+fear+negative
  autumn:        34,  // anticipation+sadness
  awesome:      594,  // anticipation+joy+surprise+positive
  awaken:       594,  // anticipation+joy+surprise+positive

  // --- B ---
  battle:       265,  // anger+fear+negative
  beautiful:    656,  // joy+trust+positive
  beauty:       656,  // joy+trust+positive
  begin:        530,  // anticipation+joy+positive
  believe:      642,  // anticipation+trust+positive
  beloved:      656,  // joy+trust+positive
  betray:       301,  // anger+disgust+fear+sadness+negative
  betrayal:     301,  // anger+disgust+fear+sadness+negative
  bitter:       293,  // anger+disgust+sadness+negative
  bliss:        656,  // joy+trust+positive
  blissful:     656,  // joy+trust+positive
  bless:        656,  // joy+trust+positive
  blessed:      656,  // joy+trust+positive
  bloom:        530,  // anticipation+joy+positive
  blossom:      530,  // anticipation+joy+positive
  blood:        269,  // anger+disgust+fear+negative
  brave:        642,  // anticipation+trust+positive
  break:        296,  // fear+sadness+negative
  breeze:       656,  // joy+trust+positive
  bright:       530,  // anticipation+joy+positive
  brilliant:    656,  // joy+trust+positive
  broken:       288,  // sadness+negative
  burden:       296,  // fear+sadness+negative
  burn:         265,  // anger+fear+negative

  // --- C ---
  cage:         296,  // fear+sadness+negative
  calm:         640,  // trust+positive
  care:         656,  // joy+trust+positive
  carefree:     528,  // joy+positive
  celebrate:    594,  // anticipation+joy+surprise+positive
  celebration:  594,  // anticipation+joy+surprise+positive
  chains:       296,  // fear+sadness+negative
  chaos:        329,  // anger+fear+surprise+negative
  cheerful:     528,  // joy+positive
  cherish:      656,  // joy+trust+positive
  clarity:      640,  // trust+positive
  cold:         288,  // sadness+negative
  collapse:     296,  // fear+sadness+negative
  comfort:      656,  // joy+trust+positive
  compassion:   656,  // joy+trust+positive
  conflict:     265,  // anger+fear+negative
  connect:      656,  // joy+trust+positive
  conquer:      658,  // anticipation+joy+trust+positive
  contentment:  656,  // joy+trust+positive
  control:      642,  // anticipation+trust+positive
  corrupt:      261,  // anger+disgust+negative
  courage:      642,  // anticipation+trust+positive
  create:       658,  // anticipation+joy+trust+positive
  creative:     658,  // anticipation+joy+trust+positive
  cruel:        261,  // anger+disgust+negative
  cruelty:      261,  // anger+disgust+negative
  cry:          288,  // sadness+negative
  curse:        269,  // anger+disgust+fear+negative

  // --- D ---
  dance:        528,  // joy+positive
  danger:       264,  // fear+negative
  dark:         264,  // fear+negative
  darkness:     296,  // fear+sadness+negative
  dawn:         530,  // anticipation+joy+positive
  dead:         296,  // fear+sadness+negative
  death:        296,  // fear+sadness+negative
  deceive:      261,  // anger+disgust+negative
  deception:    261,  // anger+disgust+negative
  defeat:       288,  // sadness+negative
  delight:      530,  // anticipation+joy+positive
  delightful:   656,  // joy+trust+positive
  demon:        268,  // disgust+fear+negative
  depress:      288,  // sadness+negative
  depression:   288,  // sadness+negative
  depressed:    288,  // sadness+negative
  desolate:     296,  // fear+sadness+negative
  despair:      296,  // fear+sadness+negative
  desperate:    296,  // fear+sadness+negative
  destroy:      269,  // anger+disgust+fear+negative
  devoted:      656,  // joy+trust+positive
  devotion:     656,  // joy+trust+positive
  die:          296,  // fear+sadness+negative
  dignity:      656,  // joy+trust+positive
  disappoint:   288,  // sadness+negative
  disaster:     300,  // disgust+fear+sadness+negative
  discover:     594,  // anticipation+joy+surprise+positive
  disgrace:     293,  // anger+disgust+sadness+negative
  disgust:      261,  // anger+disgust+negative
  divine:       656,  // joy+trust+positive
  doubt:        296,  // fear+sadness+negative
  dread:        264,  // fear+negative
  dream:        530,  // anticipation+joy+positive
  drown:        296,  // fear+sadness+negative
  dull:         288,  // sadness+negative
  dust:         288,  // sadness+negative

  // --- E ---
  eager:        642,  // anticipation+trust+positive
  ecstasy:      592,  // joy+surprise+positive
  elation:      592,  // joy+surprise+positive
  embrace:      656,  // joy+trust+positive
  emerge:       594,  // anticipation+joy+surprise+positive
  empower:      642,  // anticipation+trust+positive
  empty:        288,  // sadness+negative
  enchant:      594,  // anticipation+joy+surprise+positive
  endure:       642,  // anticipation+trust+positive
  energetic:    514,  // anticipation+positive
  enjoy:        528,  // joy+positive
  enlighten:    658,  // anticipation+joy+trust+positive
  enemy:        269,  // anger+disgust+fear+negative
  envy:         293,  // anger+disgust+sadness+negative
  escape:       328,  // fear+surprise+negative
  eternal:      656,  // joy+trust+positive
  eternity:     656,  // joy+trust+positive
  euphoria:     592,  // joy+surprise+positive
  evil:         269,  // anger+disgust+fear+negative
  excellent:    640,  // trust+positive
  exile:        288,  // sadness+negative
  exciting:     594,  // anticipation+joy+surprise+positive
  explosive:    321,  // anger+surprise+negative
  explore:      530,  // anticipation+joy+positive

  // --- F ---
  fade:         288,  // sadness+negative
  fail:         296,  // fear+sadness+negative
  failure:      296,  // fear+sadness+negative
  faith:        642,  // anticipation+trust+positive
  faithful:     640,  // trust+positive
  family:       656,  // joy+trust+positive
  fantastic:    592,  // joy+surprise+positive
  fear:         264,  // fear+negative
  festive:      530,  // anticipation+joy+positive
  fight:        265,  // anger+fear+negative
  filth:        260,  // disgust+negative
  filthy:       260,  // disgust+negative
  fire:          74,  // anticipation+fear+surprise (complex element)
  flame:        594,  // anticipation+joy+surprise+positive
  flourish:     658,  // anticipation+joy+trust+positive
  flow:         656,  // joy+trust+positive
  flower:       656,  // joy+trust+positive
  fly:          594,  // anticipation+joy+surprise+positive
  forgive:      656,  // joy+trust+positive
  forgiveness:  656,  // joy+trust+positive
  forlorn:      296,  // fear+sadness+negative
  forsaken:     296,  // fear+sadness+negative
  fortune:      658,  // anticipation+joy+trust+positive
  foul:         260,  // disgust+negative
  fraud:        261,  // anger+disgust+negative
  free:         594,  // anticipation+joy+surprise+positive
  freedom:      594,  // anticipation+joy+surprise+positive
  friend:       656,  // joy+trust+positive
  friendship:   656,  // joy+trust+positive
  frightened:   264,  // fear+negative
  frustration:  257,  // anger+negative
  furious:      261,  // anger+disgust+negative
  fury:         261,  // anger+disgust+negative

  // --- G ---
  generous:     656,  // joy+trust+positive
  gentle:       656,  // joy+trust+positive
  ghost:        328,  // fear+surprise+negative
  gift:         658,  // anticipation+joy+trust+positive
  glad:         528,  // joy+positive
  glee:         592,  // joy+surprise+positive
  gloom:        288,  // sadness+negative
  gloomy:       288,  // sadness+negative
  glorious:     658,  // anticipation+joy+trust+positive
  glow:         530,  // anticipation+joy+positive
  golden:       530,  // anticipation+joy+positive
  good:         656,  // joy+trust+positive
  grace:        656,  // joy+trust+positive
  grateful:     656,  // joy+trust+positive
  gratitude:    656,  // joy+trust+positive
  grave:        296,  // fear+sadness+negative
  grief:        288,  // sadness+negative
  grieve:       288,  // sadness+negative
  grow:         530,  // anticipation+joy+positive
  growth:       658,  // anticipation+joy+trust+positive
  guilt:        292,  // disgust+sadness+negative
  guilty:       292,  // disgust+sadness+negative

  // --- H ---
  happiness:    656,  // joy+trust+positive
  happy:        656,  // joy+trust+positive
  harm:         269,  // anger+disgust+fear+negative
  harmony:      656,  // joy+trust+positive
  hate:         261,  // anger+disgust+negative
  hatred:       261,  // anger+disgust+negative
  heal:         656,  // joy+trust+positive
  healing:      656,  // joy+trust+positive
  heart:        656,  // joy+trust+positive
  heaven:       656,  // joy+trust+positive
  helpless:     296,  // fear+sadness+negative
  heroic:       658,  // anticipation+joy+trust+positive
  hesitate:     264,  // fear+negative
  hollow:       288,  // sadness+negative
  home:         656,  // joy+trust+positive
  honest:       640,  // trust+positive
  honesty:      640,  // trust+positive
  honor:        658,  // anticipation+joy+trust+positive
  hope:         658,  // anticipation+joy+trust+positive
  hopeful:      658,  // anticipation+joy+trust+positive
  hopeless:     296,  // fear+sadness+negative
  horrible:     268,  // disgust+fear+negative
  horror:       269,  // anger+disgust+fear+negative
  hostile:      257,  // anger+negative
  hug:          656,  // joy+trust+positive
  humble:       640,  // trust+positive
  humiliate:    293,  // anger+disgust+sadness+negative
  hunger:       288,  // sadness+negative
  hurt:         265,  // anger+fear+negative

  // --- I ---
  illuminate:   530,  // anticipation+joy+positive
  imagine:      530,  // anticipation+joy+positive
  innocent:     656,  // joy+trust+positive
  innocence:    656,  // joy+trust+positive
  inspire:      658,  // anticipation+joy+trust+positive
  inspiration:  658,  // anticipation+joy+trust+positive
  injustice:    261,  // anger+disgust+negative
  insult:       261,  // anger+disgust+negative
  integrity:    640,  // trust+positive
  isolation:    288,  // sadness+negative

  // --- J ---
  jealous:      293,  // anger+disgust+sadness+negative
  jealousy:     293,  // anger+disgust+sadness+negative
  journey:      530,  // anticipation+joy+positive
  joy:          592,  // joy+surprise+positive
  joyful:       656,  // joy+trust+positive
  jubilant:     594,  // anticipation+joy+surprise+positive
  justice:      640,  // trust+positive

  // --- K ---
  kill:         269,  // anger+disgust+fear+negative
  kind:         656,  // joy+trust+positive
  kindness:     656,  // joy+trust+positive
  knowledge:    640,  // trust+positive

  // --- L ---
  lament:       288,  // sadness+negative
  laugh:        592,  // joy+surprise+positive
  laughter:     592,  // joy+surprise+positive
  learn:        658,  // anticipation+joy+trust+positive
  liberation:   594,  // anticipation+joy+surprise+positive
  life:         658,  // anticipation+joy+trust+positive
  light:        656,  // joy+trust+positive
  lonely:       288,  // sadness+negative
  loneliness:   288,  // sadness+negative
  loss:         288,  // sadness+negative
  lost:         296,  // fear+sadness+negative
  love:         658,  // anticipation+joy+trust+positive
  lovely:       656,  // joy+trust+positive
  loyal:        640,  // trust+positive
  loyalty:      640,  // trust+positive
  luminous:     530,  // anticipation+joy+positive

  // --- M ---
  magic:        594,  // anticipation+joy+surprise+positive
  magical:      594,  // anticipation+joy+surprise+positive
  magnificent:  656,  // joy+trust+positive
  malice:       261,  // anger+disgust+negative
  manipulate:   261,  // anger+disgust+negative
  marvel:       594,  // anticipation+joy+surprise+positive
  meaning:      658,  // anticipation+joy+trust+positive
  melancholy:   288,  // sadness+negative
  mercy:        656,  // joy+trust+positive
  merry:        528,  // joy+positive
  miracle:      594,  // anticipation+joy+surprise+positive
  miserable:    288,  // sadness+negative
  misery:       288,  // sadness+negative
  miss:         288,  // sadness+negative
  monster:      268,  // disgust+fear+negative
  moon:         658,  // anticipation+joy+trust+positive
  mourn:        288,  // sadness+negative
  mourning:     288,  // sadness+negative
  murder:       269,  // anger+disgust+fear+negative
  mysterious:    74,  // anticipation+fear+surprise
  mystery:       74,  // anticipation+fear+surprise

  // --- N ---
  nasty:        261,  // anger+disgust+negative
  nausea:       260,  // disgust+negative
  nervous:      328,  // fear+surprise+negative
  nightmare:    300,  // disgust+fear+sadness+negative
  noble:        656,  // joy+trust+positive
  numb:         288,  // sadness+negative

  // --- O ---
  ocean:        640,  // trust+positive
  oppression:   269,  // anger+disgust+fear+negative
  outrage:      261,  // anger+disgust+negative
  overcome:     658,  // anticipation+joy+trust+positive

  // --- P ---
  pain:         296,  // fear+sadness+negative
  panic:        329,  // anger+fear+surprise+negative
  paradise:     656,  // joy+trust+positive
  passion:      530,  // anticipation+joy+positive
  passionate:   530,  // anticipation+joy+positive
  patience:     640,  // trust+positive
  peace:        656,  // joy+trust+positive
  peaceful:     656,  // joy+trust+positive
  perfect:      640,  // trust+positive
  perseverance: 642,  // anticipation+trust+positive
  phobia:       268,  // disgust+fear+negative
  playful:      528,  // joy+positive
  pleasure:     656,  // joy+trust+positive
  poison:       268,  // disgust+fear+negative
  power:        642,  // anticipation+trust+positive
  prayer:       658,  // anticipation+joy+trust+positive
  precious:     656,  // joy+trust+positive
  pride:        658,  // anticipation+joy+trust+positive
  protect:      640,  // trust+positive
  pure:         656,  // joy+trust+positive
  purpose:      642,  // anticipation+trust+positive

  // --- Q ---
  quiet:        640,  // trust+positive

  // --- R ---
  radiant:      530,  // anticipation+joy+positive
  rage:         261,  // anger+disgust+negative
  rain:         288,  // sadness+negative
  rainbow:      592,  // joy+surprise+positive
  rebel:        259,  // anger+anticipation+negative
  regret:       288,  // sadness+negative
  rejoice:      594,  // anticipation+joy+surprise+positive
  relief:       656,  // joy+trust+positive
  remorse:      288,  // sadness+negative
  renewal:      658,  // anticipation+joy+trust+positive
  repulsive:    261,  // anger+disgust+negative
  resentment:   293,  // anger+disgust+sadness+negative
  resilient:    658,  // anticipation+joy+trust+positive
  respect:      640,  // trust+positive
  restore:      656,  // joy+trust+positive
  revenge:      261,  // anger+disgust+negative
  revolt:       269,  // anger+disgust+fear+negative
  rise:         530,  // anticipation+joy+positive
  romance:      658,  // anticipation+joy+trust+positive
  ruin:         301,  // anger+disgust+fear+sadness+negative
  ruthless:     261,  // anger+disgust+negative

  // --- S ---
  sacred:       656,  // joy+trust+positive
  sacrifice:    288,  // sadness+negative
  salvation:    658,  // anticipation+joy+trust+positive
  savage:       269,  // anger+disgust+fear+negative
  scared:       264,  // fear+negative
  scream:       329,  // anger+fear+surprise+negative
  secure:       640,  // trust+positive
  serenity:     656,  // joy+trust+positive
  serene:       656,  // joy+trust+positive
  shadow:       264,  // fear+negative
  shame:        292,  // disgust+sadness+negative
  shine:        530,  // anticipation+joy+positive
  shiver:       328,  // fear+surprise+negative
  shock:        320,  // surprise+negative
  silence:      288,  // sadness+negative
  sincere:      640,  // trust+positive
  sinister:     269,  // anger+disgust+fear+negative
  smile:        528,  // joy+positive
  soar:         594,  // anticipation+joy+surprise+positive
  sob:          288,  // sadness+negative
  song:         658,  // anticipation+joy+trust+positive
  sorrow:       288,  // sadness+negative
  sorrowful:    288,  // sadness+negative
  soul:         658,  // anticipation+joy+trust+positive
  spark:        530,  // anticipation+joy+positive
  splendid:     656,  // joy+trust+positive
  spring:       530,  // anticipation+joy+positive
  star:         592,  // joy+surprise+positive
  strength:     642,  // anticipation+trust+positive
  strive:       658,  // anticipation+joy+trust+positive
  strong:       640,  // trust+positive
  struggle:     297,  // anger+fear+sadness+negative
  success:      642,  // anticipation+trust+positive
  suffer:       296,  // fear+sadness+negative
  sun:          528,  // joy+positive
  sunrise:      658,  // anticipation+joy+trust+positive
  sunshine:     530,  // anticipation+joy+positive
  survive:      538,  // anticipation+fear+joy+positive
  sweet:        656,  // joy+trust+positive

  // --- T ---
  tears:        288,  // sadness+negative
  tender:       656,  // joy+trust+positive
  terror:       265,  // anger+fear+negative
  terrify:      264,  // fear+negative
  thankful:     656,  // joy+trust+positive
  thrive:       658,  // anticipation+joy+trust+positive
  tired:        288,  // sadness+negative
  torment:      297,  // anger+fear+sadness+negative
  torture:      269,  // anger+disgust+fear+negative
  tragedy:      288,  // sadness+negative
  tragic:       288,  // sadness+negative
  traitor:      269,  // anger+disgust+fear+negative
  trapped:      296,  // fear+sadness+negative
  trauma:       296,  // fear+sadness+negative
  treasure:     658,  // anticipation+joy+trust+positive
  tremble:      328,  // fear+surprise+negative
  triumph:      658,  // anticipation+joy+trust+positive
  trust:        642,  // anticipation+trust+positive
  truth:        640,  // trust+positive

  // --- U ---
  ugly:         260,  // disgust+negative
  uncertain:    328,  // fear+surprise+negative
  unfair:       261,  // anger+disgust+negative
  unhappy:      288,  // sadness+negative
  union:        656,  // joy+trust+positive
  unity:        656,  // joy+trust+positive

  // --- V ---
  valor:        658,  // anticipation+joy+trust+positive
  vanish:       296,  // fear+sadness+negative
  vengeance:    261,  // anger+disgust+negative
  vibrant:      530,  // anticipation+joy+positive
  vicious:      261,  // anger+disgust+negative
  victory:      658,  // anticipation+joy+trust+positive
  vile:         261,  // anger+disgust+negative
  villain:      269,  // anger+disgust+fear+negative
  violence:     269,  // anger+disgust+fear+negative
  violent:      269,  // anger+disgust+fear+negative
  virtue:       656,  // joy+trust+positive
  vulnerable:   296,  // fear+sadness+negative

  // --- W ---
  war:          269,  // anger+disgust+fear+negative
  warm:         656,  // joy+trust+positive
  warmth:       656,  // joy+trust+positive
  weep:         288,  // sadness+negative
  whisper:      640,  // trust+positive
  wicked:       269,  // anger+disgust+fear+negative
  wisdom:       640,  // trust+positive
  wise:         640,  // trust+positive
  wonder:       594,  // anticipation+joy+surprise+positive
  wonderful:    656,  // joy+trust+positive
  worry:        296,  // fear+sadness+negative
  wound:        296,  // fear+sadness+negative
  wrath:        261,  // anger+disgust+negative
  wretched:     288,  // sadness+negative

  // --- Y ---
  yearn:         34,  // anticipation+sadness
};
